services:
  itvdelab:
    image: itversity/itvdelab
    hostname: itvdelab
    ports:
      - "8888:8888"
      - "9879:9870"
      - "4040:4040"
      - "8078:8088"
      - "18180:18080"
      - "18181:18081"
    volumes:
      - "./itversity-material:/home/itversity/itversity-material"
      - "./data:/data"
    environment:
      SHELL: /bin/bash
    networks:
      - itvdelabnw
    depends_on:
      - "cluster_util_db"

  cluster_util_db:
    image: postgres:13
    ports:
      - "6432:5432"
    volumes:
      - ./cluster_util_db_scripts:/docker-entrypoint-initdb.d
    networks:
      - itvdelabnw
    environment:
      POSTGRES_PASSWORD: itversity
      
  metabase:
    image: metabase/metabase:latest
    ports:
      - "3001:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabasepassword
      MB_DB_HOST: metabase_db
    networks:
      - itvdelabnw
    depends_on:
      - metabase_db

  metabase_db:
    image: postgres:13
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabasepassword
    volumes:
      - metabase_data:/var/lib/postgresql/data
    networks:
      - itvdelabnw

  hbase:
    image: harisekhon/hbase:1.3
    ports:
      - "16000:16000"
      - "16010:16010"
      - "16020:16020"
      - "16030:16030"
    environment:
      HBASE_CONF_hbase_rootdir: hdfs://itvdelab:9000/hbase
      HBASE_CONF_hbase_zookeeper_quorum: itvdelab
    networks:
      - itvdelabnw
    depends_on:
      - itvdelab


networks:
  itvdelabnw:
    name: itvdelabnw

volumes:
  metabase_data:
